### ISSUE TITLE
Remove the hashtag ID (e.g. #3) in the title and replace with creation date

### ISSUE THREAD

**Issue by KentShikama** [KentZiqi/OFiction#5]

**Comment by ZiqiXiong** [comment]
Won't that make title too long? Hashtag ID is a way to identify a node in a tree (in the order to creation date). I don't see why we need to replace that with creation date itself.

**Comment by KentShikama** [comment]
Hmm yeah. I guess we can leave it. We may want to deemphasize it just like Github does.
